### PR TITLE
Don't read HTTP entire response body unnecessarily, take 2

### LINKED ISSUE #379: Client.do always read entire response body, which might waste memory
This has been reported and fixed in the PR #375, but as reported in #378, the fix introduced another bug: because of the ``defer dial.Close()`` call, only the first 4k bytes were available in the body, and then reading the body fails with "use of closed network connection".

We should come with a solution where Client.do don't read entire body and we don't leak file descriptors (maybe handling the socket closing in each caller of Client.do).

### PR DESCRIPTION
**Pull request by chuyeow**
Fixes #379, follow up to the reverted #375.

`Client.do()` now does not read the entire HTTP response from the Docker remote API, since that is an unnecessary memory / allocation burden. Instead, it returns the `*http.Response` and relies on callers to read / copy from / close the body as necessary.

When connecting to Docker via UNIX domain socket, we use a fake `http.Client` that dials to the socket, thus fixing the issue reported in #378 where the underlying network connection was prematurely closed when the HTTP response (+headers) does not fit into the default 4096-byte buffer.

### CODE REVIEW

File: client.go [hunk 1]
```diff
@@ -669,6 +657,41 @@ func (c *Client) getURL(path string) string {
...
+func (c *Client) unixClient() *http.Client {
+	if c.unixHTTPClient != nil {
+		return c.unixHTTPClient
+	}
+
+	socketPath := c.endpointURL.Path
+	c.unixHTTPClient = &http.Client{
+		Transport: &http.Transport{
+			Dial: func(network, addr string) (net.Conn, error) {
+				return net.Dial("unix", socketPath)
```
Comment (fsouza) [inline client.go]: Can you use c.Dialer.Dial instead of net.Dial here?

Dialer has been added to support certain customization, and we don't wanna bypass it here.

Just this change and I believe it's good to merge. Thank you very much for working on this!

Comment (chuyeow) [inline client.go]: Ah you're right, I missed that. Thanks for pointing it out - fixed.

**Comment by fsouza** [comment]
Thank you!
